apiVersion: v1
kind: PersistentVolume
metadata:
  name: idata-pv
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadOnlyMany
  capacity: 
    storage: 100Gi
  hostPath:
    path: {{ .Values.global.idata_path }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: idata-pv-claim
spec:
  storageClassName: manual
  volumeName: idata-pv
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 3Gi
