version: "3"
services:
    auditbeat:
        build:
            context: ./auditbeat
        container_name: auditbeat
        volumes:
            - /srv/idata:/srv/idata
    logstash:
        build:
            context: ./logstash
        container_name: logstash
    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"
        volumes:
            - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
            - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    idata-metadata:
        build: ../idata-metadata 
        container_name: idata-metadata
        depends_on:
            - rabbitmq
        command: ["./wait-for-it.sh", "rabbitmq:5672", "--", "python", "processfile.py"]
        #tty: true

