apiVersion: v1
kind: PersistentVolumeClaim
metadata:
        name: rabbitmq-pvc
spec:
        resources:
                requests:
                        storage: 8Gi
        accessModes:
        - ReadWriteOnce
        storageClassName: ""
