apiVersion: v1
kind: PersistentVolume
metadata:
        name: rabbitmq-pv
spec:
        capacity:
                storage: 16Gi
        accessModes:
        - ReadWriteOnce
        - ReadOnlyMany
        persistentVolumeReclaimPolicy: Retain
        #storageClassName: manual
        nfs:
                server: 149.165.171.191
                path: "/vol_b/nfs"

