apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-load-definition
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
stringData:
  load_definition.json: |-
    { 
      "vhosts": [
        { 
          "name": "/"
        }
      ],
      "users": [
        {  
           "name": {{ .Values.global.rabbitmq_username | quote }},
           "password": {{ .Values.global.rabbitmq_password | quote }},
           "tags": "administrator",
        }
      ],
      "permissions": [
        {  
           "user": "rabbitmq",
           "vhost": "/",
           "configure": ".*",
           "write": ".*",
           "read": ".*"
        }
      ],
      "policies": [
        { 
          "name": "ha-geoedf",
          "apply-to": "queues",
          "definition": {
             "ha-mode": "exactly",
             "ha-params": 2,
             "ha-sync-mode": "automatic"
           },
           "pattern": "^geoedf",
           "priority": 0,
           "vhost": "/"
        }
      ],
      "exchanges": [
        { 
          "name": "geoedf-all",
          "vhost": "/",
          "type": "direct",
          "durable": true,
          "auto_delete": false,
          "internal": false,
          "arguments": {}
        }
      ],
      "queues": [                                                                                                                                                                                                                                                                       {                                                                                                                                                                                                                                                                                 "name": "geoedf-all",                                                                                                                                                                                                                                                           "vhost": "/",                                                                                                                                                                                                                                                                   "durable": true,                                                                                                                                                                                                                                                                "auto_delete": false,                                                                                                                                                                                                                                                           "arguments": {}                                                                                                                                                                                                                                                               }                                                                                                                                                                                                                                                                             ],                                                                                                                                                                                                                                                                              "bindings": [                                                                                                                                                                                                                                                                     {                                                                                                                                                                                                                                                                                 "source": "geoedf-all",                                                                                                                                                                                                                                                         "vhost": "/",                                                                                                                                                                                                                                                                   "destination": "geoedf-all",                                                                                                                                                                                                                                                    "destination_type": "queue",                                                                                                                                                                                                                                                    "routing_key": "geoedf",                                                                                                                                                                                                                                              
          "arguments": {}
        }
      ]
    }
